name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Frontend build
        working-directory: retreivo-frontend
        run: |
          npm ci
          npm run build
      - name: Backend install
        working-directory: retreivo-backend
        run: npm ci
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: ML install
        working-directory: ml-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt








